//tealium universal tag - utag.418 ut4.0.202307270536, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){var UTM_KEYS=["utm_campaign","utm_source","utm_medium","utm_term","utm_content","utm_audience","gclid","referrer"],UTM_PRIMARY=UTM_KEYS[0],UTM_VALIDATE=UTM_KEYS[1],UTM_FLAG="VC_",MARKETO_COOKIE_FIELD_SUFFIX="__c",VISITOR_ID_COOKIE_NAME="VC_visitor",MAX_AGE=60*60*24*120,RELEVANT_DOMAINS=["logitech","logicool"],REFERRER_KEY="referrer",BG_PREFIXES=["AG","BL","CPC","CPM","CPP","CPW","CPE","CPMX","CPX","CV","EC","GA","LAH","JB","UE","VC","MO","LAS"];var BG_PREFIX_REGEX=new RegExp("^("+BG_PREFIXES.join("_|")+"_)");var getUTMParams=function(qs){var utmObj=null;if(!qs||qs==="?")return null;qs=(qs.startsWith("?")?qs.substr(1):qs).split("&");qs.forEach(function(item){item=item.split("=");if(UTM_KEYS.includes(item[0])){if(!utmObj){utmObj={};}
utmObj[item[0]]=item[1];}});return utmObj;};var readCookie=function(name){var valsRegEx=new RegExp("(?:(?:^|.*;\\s*)"+name+"\\s*\\=\\s*([^;]*).*$)|^.*$");return document.cookie.replace(valsRegEx,"$1");};var getStoredValues=function(){var utmObj=null;UTM_KEYS.forEach(function(utmkey){var utmval=readCookie(UTM_FLAG+utmkey);if(utmval){if(!utmObj){utmObj={};}
utmObj[utmkey]=utmval;}});return utmObj;};var storeUTMvals=function(valsObj){UTM_KEYS.forEach(function(item){document.cookie=UTM_FLAG+item+"="+valsObj[item]+";domain="+getDomain()+";max-age="+((valsObj[item]===undefined)?0:MAX_AGE)+";path=/";});};var getDomain=function(url){var domain,relIdx;if(url===""){return null;}
url=new URL(url||document.location.href);domain=url.hostname.split(".");relIdx=domain.findIndex(function(elem){return RELEVANT_DOMAINS.includes(elem);});if(relIdx>0){domain.splice(0,relIdx);}
return domain.join(".");};var updateMarketoForms=function(){var vcCookies=getStoredValues();UTM_KEYS.forEach(function(param){if(typeof vcCookies[param]!=='undefined'){var fieldId=param+MARKETO_COOKIE_FIELD_SUFFIX;var $hiddenField=jQuery("[name="+fieldId+"]");var hiddenVal=vcCookies[param];$hiddenField.val(hiddenVal);}});};var init=function(){var utmVals=getUTMParams(window.location.search);if(utmVals){storeUTMvals(utmVals);updateMarketoForms();}
prevURL=document.referrer;if(typeof prevURL!=="undefined"&&prevURL!=""){let referrerDomain=getDomain(prevURL);let myDomain=getDomain();if(referrerDomain!=myDomain){existing=getStoredValues();if(!existing||!existing[REFERRER_KEY]){if(!existing){existing={};}
existing[REFERRER_KEY]=prevURL.substr(0,255);storeUTMvals(existing);updateMarketoForms();}}}
setTimeout(function(){var mcid=(typeof visitor!=='undefined'&&typeof visitor.getMarketingCloudVisitorID!=='undefined')?visitor.getMarketingCloudVisitorID():null;if(mcid!==null){document.cookie=VISITOR_ID_COOKIE_NAME+"="+mcid+";domain="+getDomain()+";max-age="+MAX_AGE+";path=/";}},500);};init();}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("418","logitech.main");}catch(error){utag.DB(error);}
