//tealium universal tag - utag.659 ut4.0.202307270536, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){if(utag.data.page_type==="Homepage"||(window.location.href.indexOf("search.html")>-1)){window.dtm_config={dtmc_department:utag.data.page_category_name};}
else if(utag.data.page_type=="PLP"||utag.data.page_type=="subcat"||utag.data.page_type=="products"){window.dtm_config={dtmc_department:utag.data.page_category_name,dtmc_sub_category:utag.data.page_subcategory_name,dtmc_category:utag.data.product_category};}
else if(utag.data.page_type=="pdp"||utag.data.page_type=="detail"||utag.data.page_type=="PDP"||utag.data.page_type=="ShoppingCart"||utag.data.page_type.indexOf("Shopping_Cart")>-1){window.dtm_config={dtmc_department:utag.data.page_category_name,dtmc_sub_category:utag.data.product_sub_category,dtmc_category:utag.data.product_category,dtmc_product_id:utag.data.product_id[0],dtmc_sku:utag.data.product_sku_short[0]};}
else if(utag.data.page_type==="Order_Complete"||utag.data.order_id!==undefined){var totalOrderValue=0;if(typeof utag.data.order_subtotal!=='undefined'){totalOrderValue=Number(utag.data.order_subtotal);}
var addProductCount=utag.data.product_sku_short.length||1;var contentArray=[];for(var dex=0;dex<1;dex++){var sku=(dex<utag.data.product_sku_short.length)?utag.data.product_sku_short[dex]:"";var prodname=(dex<utag.data.product_id.length)?utag.data.product_id[dex]:"";var price=(dex<utag.data.product_unit_price.length)?utag.data.product_unit_price[dex]:"";var quantity=(dex<utag.data.product_quantity.length)?utag.data.product_quantity[dex]:"1";var discount=(dex<utag.data.product_discount.length)?utag.data.product_discount[dex]:"0";var content={product_id:prodname,item_quantity:quantity,item_amount:price,item_discount:discount}
contentArray.push(content);}
window.dtm_config={dtmc_transaction_id:utag.data.order_id,dtm_conv_val:totalOrderValue,dtm_conv_curr:"USD",dtm_items:contentArray};}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var cachebuster=Math.round(new Date().getTime()/1000);var promo_id=0;var dtmFID=101;if(utag.data.page_type==="Homepage")
promo_id="1";else if(utag.data.page_type=="PLP"||utag.data.page_type=="subcat"||utag.data.page_type=="products")
promo_id="3";else if(utag.data.page_type=="pdp"||utag.data.page_type=="detail"||utag.data.page_type=="PDP")
promo_id="2";else if((window.location.href.indexOf("search.html")>-1))
promo_id="7";else if(utag.data.page_name=="ShoppingCart"||utag.data.page_name.indexOf("Shopping_Cart")>-1)
promo_id="6";else if(utag.data.page_name==="Order_Complete"||utag.data.order_id!==undefined){promo_id="100";dtmFID=102;}
var epsilonSrc="https://login.dotomi.com/profile/visit/js/1_0?dtm_cid=82483&dtm_cmagic=216c7a&dtm_fid="+dtmFID+"&dtm_promo_id="+promo_id+"&cachebuster="+cachebuster;(function(){var epsilon=document.createElement('script');epsilon.type='text/javascript';epsilon.async=true;epsilon.referrerPolicy='unsafe-url';epsilon.src=epsilonSrc;var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(epsilon,s);})();}};utag.o[loader].loader.LOAD(id);})("659","logitech.main");}catch(error){utag.DB(error);}
