//tealium universal tag - utag.581 ut4.0.202307270536, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(utag.data.site_id==='logi')
!function(){window.tkrc=window.tkrc||[];var tkrc=window.tkrc;if(!tkrc.initialize)if(tkrc.invoked)window.console&&console.error;else{tkrc.invoked=!0,tkrc.methods=["event"],tkrc.factory=function(t){return function(){for(var e=arguments.length,n=new Array(e),r=0;r<e;r++)n[r]=arguments[r];return n.unshift(t),tkrc.push(n),tkrc}};for(var t=0;t<tkrc.methods.length;t++){var e=tkrc.methods[t];tkrc[e]=tkrc.factory(e)}tkrc.load=function(){var t=document.createElement("script");t.type="text/javascript",t.defer=!0,t.src="".concat("https://cdn.tkrconnector.com/js/tkrc.js");document.body.appendChild(t)},tkrc.options={cookieDomain:'logitech.com'},tkrc.load()}}();else if(utag.data.site_id==='gaming')
!function(){window.tkrc=window.tkrc||[];var tkrc=window.tkrc;if(!tkrc.initialize)if(tkrc.invoked)window.console&&console.error;else{tkrc.invoked=!0,tkrc.methods=["event"],tkrc.factory=function(t){return function(){for(var e=arguments.length,n=new Array(e),r=0;r<e;r++)n[r]=arguments[r];return n.unshift(t),tkrc.push(n),tkrc}};for(var t=0;t<tkrc.methods.length;t++){var e=tkrc.methods[t];tkrc[e]=tkrc.factory(e)}tkrc.load=function(){var t=document.createElement("script");t.type="text/javascript",t.defer=!0,t.src="".concat("https://cdn.tkrconnector.com/js/tkrc.js");document.body.appendChild(t)},tkrc.options={cookieDomain:'logitechg.com'},tkrc.load()}}();else if(utag.data.site_id==='astro')
!function(){window.tkrc=window.tkrc||[];var tkrc=window.tkrc;if(!tkrc.initialize)if(tkrc.invoked)window.console&&console.error;else{tkrc.invoked=!0,tkrc.methods=["event"],tkrc.factory=function(t){return function(){for(var e=arguments.length,n=new Array(e),r=0;r<e;r++)n[r]=arguments[r];return n.unshift(t),tkrc.push(n),tkrc}};for(var t=0;t<tkrc.methods.length;t++){var e=tkrc.methods[t];tkrc[e]=tkrc.factory(e)}tkrc.load=function(){var t=document.createElement("script");t.type="text/javascript",t.defer=!0,t.src="".concat("https://cdn.tkrconnector.com/js/tkrc.js");document.body.appendChild(t)},tkrc.options={cookieDomain:'astrogaming.com'},tkrc.load()}}();else if(utag.data.site_id==='jaybird')
!function(){window.tkrc=window.tkrc||[];var tkrc=window.tkrc;if(!tkrc.initialize)if(tkrc.invoked)window.console&&console.error;else{tkrc.invoked=!0,tkrc.methods=["event"],tkrc.factory=function(t){return function(){for(var e=arguments.length,n=new Array(e),r=0;r<e;r++)n[r]=arguments[r];return n.unshift(t),tkrc.push(n),tkrc}};for(var t=0;t<tkrc.methods.length;t++){var e=tkrc.methods[t];tkrc[e]=tkrc.factory(e)}tkrc.load=function(){var t=document.createElement("script");t.type="text/javascript",t.defer=!0,t.src="".concat("https://cdn.tkrconnector.com/js/tkrc.js");document.body.appendChild(t)},tkrc.options={cookieDomain:'jaybirdsport.com'},tkrc.load()}}();else if(utag.data.site_id==='ultimateears')
!function(){window.tkrc=window.tkrc||[];var tkrc=window.tkrc;if(!tkrc.initialize)if(tkrc.invoked)window.console&&console.error;else{tkrc.invoked=!0,tkrc.methods=["event"],tkrc.factory=function(t){return function(){for(var e=arguments.length,n=new Array(e),r=0;r<e;r++)n[r]=arguments[r];return n.unshift(t),tkrc.push(n),tkrc}};for(var t=0;t<tkrc.methods.length;t++){var e=tkrc.methods[t];tkrc[e]=tkrc.factory(e)}tkrc.load=function(){var t=document.createElement("script");t.type="text/javascript",t.defer=!0,t.src="".concat("https://cdn.tkrconnector.com/js/tkrc.js");document.body.appendChild(t)},tkrc.options={cookieDomain:'ultimateears.com'},tkrc.load()}}();if(typeof utag.data.order_id!=='undefined'){var products=utag.data['product_quantity'];var skudata=[];for(i=0;i<products.length;i++){var psku=String(utag.data.product_sku_short).split(",")[i];var pqty=parseInt(String(utag.data.product_quantity).split(",")[i],10);skudata.push({id:psku,quantity:pqty});}
var tkrcIntervalCount=0;var tkrcInterval=setInterval(function(){tkrcIntervalCount++;if(typeof window.tkrc!=='undefined'){window.tkrc.event('Purchase',{transactionId:utag.data.order_id.toString(),value:parseFloat(utag.data.order_subtotal),valueCurrency:utag.data.order_currency.toUpperCase(),products:skudata});}
if(typeof window.tkrc!=='undefined'||tkrcIntervalCount>10){clearInterval(tkrcInterval);}},200);}
}};utag.o[loader].loader.LOAD(id);})("581","logitech.main");}catch(error){utag.DB(error);}
